In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

In [2]:
df=pd.read_csv('training_data.csv')
print(f"shape:{df.shape}")
df.head()

shape:(4750, 10)

,click_count,avg_click_interval,click_interval_variance,click_interval_entropy,mouse_velocity_variance,max_element_click_rate,scroll_events,keystroke_count,persona,label
0,200,22.609732,6.132684,0.014982,0.000000,39.292982,0.0,0.0,http_flooder,bot
1,8,1524.943564,269875.235918,2.304230,0.356148,1.201258,11.0,5.0,casual_browser,human
2,4,1540.784354,254741.917130,2.607192,0.786881,1.449804,11.0,3.0,casual_browser,human
3,15,477.774439,114469.093339,2.897984,0.321347,1.323701,2.0,56.0,power_user,human
4,19,428.310760,117565.233111,2.981485,1.028971,2.472009,3.0,58.0,power_user,human

In [7]:
df.info
print("null values:",df.isnull().sum)

null values: <bound method DataFrame.sum of       click_count  avg_click_interval  click_interval_variance  \
0           False               False                    False
1           False               False                    False
2           False               False                    False
3           False               False                    False
4           False               False                    False
...           ...                 ...                      ...
4745        False               False                    False
4746        False               False                    False
4747        False               False                    False
4748        False               False                    False
4749        False               False                    False

      click_interval_entropy  mouse_velocity_variance  max_element_click_rate  \
0                      False                    False                   False
1                      False                    False                   False
2                      False                    False                   False
3                      False                    False                   False
4                      False                    False                   False
...                      ...                      ...                     ...
4745                   False                    False                   False
4746                   False                    False                   False
4747                   False                    False                   False
4748                   False                    False                   False
4749                   False                    False                   False

      scroll_events  keystroke_count  persona  label
0             False            False    False  False
1             False            False    False  False
2             False            False    False  False
3             False            False    False  False
4             False            False    False  False
...             ...              ...      ...    ...
4745          False            False    False  False
4746          False            False    False  False
4747          False            False    False  False
4748          False            False    False  False
4749          False            False    False  False

[4750 rows x 10 columns]>

In [8]:
df.describe()

,click_count,avg_click_interval,click_interval_variance,click_interval_entropy,mouse_velocity_variance,max_element_click_rate,scroll_events,keystroke_count
count,4750.000000,4750.000000,4750.000000,4750.000000,4750.000000,4750.000000,4750.000000,4750.000000
mean,19.602737,830.673581,126796.964678,2.147238,0.383493,3.592429,4.522105,19.211871
std,44.557815,433.903829,88413.766630,1.096883,0.387559,9.143032,4.074717,17.898303
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.101404,0.000000,0.000000
25%,5.000000,488.450264,62722.022356,1.816425,0.021064,0.771587,1.000000,6.250000
50%,8.000000,857.830092,133450.487458,2.498620,0.308566,1.264922,4.000000,11.000000
75%,15.000000,1120.374936,186224.835007,2.910560,0.697012,2.377436,7.000000,38.063147
max,299.000000,2258.716556,436416.804336,4.263109,1.687052,59.975886,22.000000,65.000000

In [10]:
features=[
    'click_count','avg_click_interval'
    'click_interval_variance',
    'click_interval_entropy',
    'mouse_velocity_variance',
    'max_element_click_rate',
    'scroll_events',
    'keystroke_count'
]
df.groupby('label')[features].mean().T

KeyError: "Columns not found: 'avg_click_intervalclick_interval_variance'"